baseURL = "https://yasu-yamasaki.github.io/"
languageCode = "jp"
title = "ヤス ブロ"
theme = "zozo"
hasCJKLanguage = true
enableEmoji = true

[params]
subTitle = "ハードルは下げる。ネガティブなことは書かない。"
description = "あるエンジニアの個人的なブログ"
enableSummary = true
mainSections = ["posts","post"]

[[menu.main]]
name = "Home"
weight = 10
identifier = "home"
url = "/"
[[menu.main]]
name = "Archive"
weight = 20
identifier = "archive"
url = "/posts/"
[[menu.main]]
name = "Tags"
weight = 30
identifier = "tags"
url = "/tags/"

[social]
github = "github"
twitter = "https://twitter.com/yasu_yamasaki"
facebook = "https://www.facebook.com/yasuyuki.yamasaki.79"
